# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - imagedockerfu

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://imagedockerfu.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_cb23b1730bc84eb0968ac638f0106517 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_b855df21bb854b2d8cdc468727a72ee4 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: imagedockerfu.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_cb23b1730bc84eb0968ac638f0106517 }}/imagedockerfu:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'imagedockerfu'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_1c5c056d5a48455b97c5e5effaba7ba2 }}
        images: 'imagedockerfu.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_cb23b1730bc84eb0968ac638f0106517 }}/imagedockerfu:${{ github.sha }}'